### ISSUE TITLE
Commit LICENSE file (not just README)

### ISSUE THREAD

**Issue by hochhaus** [shurcooL/sanitized_anchor_name#3]
Would you be willing to commit a dedicated LICENSE file (not just the README) noting the MIT license? Apologies for the request, but this is a requirement for some legal teams.

**Comment by dmitshur** [comment]
Hi, thanks for potentially using this package.

I have two thoughts on this:
1. I want as many people as possible to be able to benefit from this code. That's why it's open source rather than closed. You're welcome to do anything with it that's helpful to you. Also, this package is a part of [blackfriday](https://github.com/russross/blackfriday), which isn't my project, so I wouldn't want to do anything to impede others using blackfriday.
2. I really dislike polluting nice, clean, simple packages with ugly legalese boilerplate that gets in the way when actually doing useful things like developing, testing, running the code.

However, point 1 is higher priority than 2, so I will resolve this. But I wish there was a way to do that without compromising on point 2... :(

**Comment by hochhaus** [comment]
Thanks for your flexibility!

**Comment by client9** [comment]
Thank you for doing this.  I know the license stuff is annoying,
